# Generated by Django 3.2.9 on 2022-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_alter_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='link',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
        migrations.AddField(
            model_name='media',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='picture'),
        ),
    ]
