# Generated by Django 3.2.9 on 2022-01-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Twitter_ID',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
