# Generated by Django 3.2.9 on 2022-01-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220107_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Facebook_URL',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
