# Generated by Django 3.2.9 on 2022-01-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Facebook_URL',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Instagram_ID',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='TikTok_ID',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Twitter_ID',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
